# Generated by Django 4.0 on 2022-01-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('routine', '0002_alter_course_cancelled_by_alter_course_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.program'),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
