# Generated by Django 4.0 on 2022-01-21 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('routine', '0003_alter_dailyroutine_program_delete_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_routines', to='organization.program'),
        ),
    ]
