# Generated by Django 4.0 on 2022-01-24 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_course'),
        ('authentication', '0001_initial'),
        ('routine', '0004_alter_dailyroutine_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_cancelled', models.BooleanField(blank=True, default=False, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_courses', to='authentication.user')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.course')),
                ('daily_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='routine.dailyroutine')),
                ('subject_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
