# Generated by Django 4.0 on 2022-01-12 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('post_notice', 'can post notices about classes'), ('assign_assignments', 'can assign assignments to students')]},
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('classrooms', models.IntegerField(blank=True, null=True)),
                ('departments', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_joined', models.DateField(blank=True, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('classrooms', models.IntegerField(blank=True, null=True)),
                ('faculty', models.CharField(blank=True, max_length=4, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
