# Generated by Django 4.0 on 2022-01-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_invitation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('T', 'Teacher'), ('S', 'Student'), ('St', 'Staff'), ('SU', 'SuperUser')], default='S', max_length=2, null=True),
        ),
    ]
