# Generated by Django 4.0 on 2022-01-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_teacher_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='year_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
