# Generated by Django 4.0 on 2022-01-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_teacher_year_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student'), ('St', 'Staff'), ('SU', 'SuperUser')], default='S', max_length=2),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
