# Generated by Django 4.0 on 2022-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_managers_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student'), ('St', 'Staff'), ('SU', 'SuperUser')], default=None, max_length=2),
        ),
    ]
