# Generated by Django 4.0 on 2022-01-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Additional Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='add_phone_num',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_num',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Citizenship Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
