# Generated by Django 4.0.2 on 2022-02-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
