# Generated by Django 4.0.2 on 2022-03-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classroom_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'permissions': [('can_archive_classroom', 'Can Archive Classroom')]},
        ),
    ]
