# Generated by Django 4.0 on 2022-03-07 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_post_post_id_alter_post_reacted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.UUID('25055dd3-9e93-483b-a29e-6be392ba2563'), unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reacts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('2fb44572-182e-415b-ab88-dbabff2ffc1f'), unique=True),
        ),
    ]
