# Generated by Django 4.0 on 2022-03-07 08:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('classroom', '0006_alter_comment_comment_id_alter_comment_reacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentors', to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.UUID('e8aef4bf-8b88-41d7-9188-7fe5d0c5b025'), unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('755b45f3-385d-49b8-8300-ecd5ac6f3fb1'), unique=True),
        ),
    ]
