# Generated by Django 4.0 on 2022-03-07 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_alter_comment_comment_id_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.UUID('8fd8bea0-b8f0-490e-ac15-e971cd781b0d'), unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('d6290391-523b-4908-bf95-318a554b2826'), unique=True),
        ),
    ]
