# Generated by Django 4.0.2 on 2022-03-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_classroom_options'),
        ('classroom', '0010_alter_comment_comment_id_alter_post_post_id'),
    ]

    operations = [
    ]
