# Generated by Django 4.0 on 2022-02-07 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_course'),
        ('authentication', '0004_remove_user_user_role_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('details', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='assignments/')),
                ('close_date', models.DateTimeField()),
                ('points', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('file', models.FileField(upload_to='submission/')),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
