# Generated by Django 4.0 on 2022-02-07 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 7, 16, 46, 345896, tzinfo=utc)),
        ),
    ]
