# Generated by Django 4.0 on 2022-02-07 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
