# Generated by Django 4.0 on 2022-03-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classroom_created_by'),
        ('assignment', '0002_alter_assignment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
            preserve_default=False,
        ),
    ]
