# Generated by Django 4.0 on 2022-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_assignment_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='title 1', max_length=100),
            preserve_default=False,
        ),
    ]
