# Generated by Django 4.0 on 2022-01-14 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=250, unique=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('modified_on', models.DateField(blank=True, default=datetime.datetime(2022, 1, 14, 6, 48, 40, 83329, tzinfo=utc), null=True)),
                ('dep_code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_code', models.CharField(max_length=4, unique=True)),
                ('pr_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 6, 48, 40, 84252, tzinfo=utc), null=True)),
                ('year', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
