# Generated by Django 4.0 on 2022-01-14 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Program Code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='modified_on',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 14, 6, 52, 16, 903179, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='modified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 6, 52, 16, 904239, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='pr_code',
            field=models.CharField(max_length=4, unique=True, verbose_name='Program Code'),
        ),
        migrations.AlterField(
            model_name='program',
            name='pr_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Program'),
        ),
    ]
