# Generated by Django 4.0 on 2022-01-14 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_dep_code_alter_department_dep_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Department Code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='modified_on',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 14, 6, 54, 23, 609139, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='modified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 6, 54, 23, 610096, tzinfo=utc), null=True),
        ),
    ]
