# Generated by Django 4.0 on 2022-01-14 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_program_department_alter_department_dep_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='modified_on',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 14, 9, 50, 41, 841804, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='modified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 9, 50, 41, 843650, tzinfo=utc), null=True),
        ),
    ]
