# Generated by Django 4.0 on 2022-01-14 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_department_modified_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='Department',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='department',
            name='modified_on',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 14, 10, 46, 21, 225943, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='modified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 10, 46, 21, 226931, tzinfo=utc), null=True),
        ),
    ]
