# Generated by Django 4.0 on 2022-01-19 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_alter_department_modified_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='modified_on',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 19, 14, 32, 5, 225146, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='modified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 19, 14, 32, 5, 226310, tzinfo=utc), null=True),
        ),
    ]
